### ISSUE TITLE
Wrong result with u8

### ISSUE THREAD

**Issue by i64** [kaitai-io/kaitai_struct_javascript_runtime#19] opened 2020-11-03 05:16 UTC
The last byte of u8 is missing.

Example struct:
```yaml
meta:
  id: test
  endian: le

seq:
  - id: uu64
    type: u8
```

example data:
```python
"\xf7\x30\x8a\x1e\xce\xf2\xde\xe9\x12\x5f"
```

result:
- `0xE9DEF2CE1E8A3000`

expected result:
- `0xE9DEF2CE1E8A30F7`

**Comment by generalmimon** [comment] 2020-11-03 09:02
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/183

**Closed as completed by generalmimon** 2020-11-03 09:02 UTC
Labels: duplicate
